[musicbank]
title = "KBS 뮤직뱅크 ─ 네이버TV"
url = "https://tv.naver.com/musicbank?tab=clip"
entrySelector = "div.showId_panel_section__GUdI_ > div > ul > li"
titleSelector = "div > div > div.ClipCardV2_title_area__At_Y8 > a"
linkSelector = "a"
imageSelector = "a > div > span:nth-child(1) > img"
contentSelector = "a > div > span.ClipCardV2_playtime__IHYFQ"
waitForSelector = "div.showId_panel_section__GUdI_ > div > ul > li"
onFail = "stale"

