[default]
timeout = 120

[musicbank]
title = "KBS 뮤직뱅크 ─ 네이버TV"
url = "https://tv.naver.com/musicbank?tab=clip"
entrySelector = "#content > div.showId_panel_section__GUdI_ > div > ul > li"
titleSelector = "div > div > div.ClipCardV2_title_area__At_Y8 > a"
linkSelector = "div > div > div.ClipCardV2_title_area__At_Y8 > a"
waitForSelector = "#content > div.showId_panel_section__GUdI_ > div > ul > li"
onFail = "stale"
